baseURL = "https://ringil.me"
title = "Nill Ringil"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Nill Ringil"
license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Nill Ringil's personal site"
keywords = "blog,devops,sysadmin,personal,linux"
info = ["Full Stack DevOps", "Linux Administrator","Magician"]
#avatarURL = "images/avatar.jpg"
gravatar = "nill@ringil.me"
dateFormat = "January 2, 2006"
since = 2003
enableRobotsTXT = true
rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
customCSS = []
customSCSS = []
customJS = []

[params.cloudflare]
token = "469c64519bca4880983fa39c82c74cb5"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'", "https://www.gravatar.com/"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = [
  "'self'", 
  "'unsafe-inline'",
  "'unsafe-eval'",
  "https://www.google-analytics.com",
  "https://cdn.jsdelivr.net/",
  "https://static.cloudflareinsights.com",
  "https://cloudflareinsights.com",
  "https://ringil.me"
]
prefetchsrc = ["'self'"]
connectsrc = ["'self'", "https://www.google-analytics.com", "https://cloudflareinsights.com/"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/Nill-R/"

[[params.social]]
name = "Telegram"
icon = "fa fa-2x fa-telegram"
weight = 2
url = "https://t.me/sysadmnotes"

[[params.social]]
name = "Facebook"
icon = "fa fa-2x fa-facebook"
weight = 3
url = "https://facebook.com/nill.ringil/"


[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"

[languages.ru]
languageName = "РУ"
title = "Нилл Рингил"

[languages.ru.params]
author = "Нилл Рингил"
info = ["Системный администратор Linux", "Full Stack DevOps", "Маг и волшебник"]
description = "Личный сайт Нилла Рингила"
keywords = "blog,admin,devops,блог,девопс,админ,линукс,linux"

[[languages.ru.menu.main]]
name = "Обо мне"
weight = 1
url = "about/"

[[languages.ru.menu.main]]
name = "Проекты"
weight = 3
url = "projects/"

[[languages.ru.menu.main]]
name = "Контакты"
weight = 5
url = "contact/"

[languages.ua]
languageName = "🇺🇦"
title = "Нілл Рінгіл"

[languages.ua.params]
author = "Нілл Рінгіл"
info = ["Системний адміністратор Linux", "Full Stack DevOps", "Маг і чарівник"]
description = "Персональний сайт Нілла Рінгіла"
keywords = "blog,admin,devops,блог,девопс,админ,линукс,linux"

[[languages.ua.menu.main]]
name = "Про мене"
weight = 1
url = "about/"

[[languages.ua.menu.main]]
name = "Проекти"
weight = 3
url = "projects/"

[[languages.ua.menu.main]]
name = "Контакти"
weight = 5
url = "contact/"

